### ISSUE TITLE
Save States vs. Battery Files

### ISSUE THREAD

**Issue by The-Box1** [ardean/jsGBC-core#14]
What's the difference between save states and battery files? Which one saves the current progress in the game?

**Comment by ardean** [comment]
Save states are memory snapshots and store the current memory of the Gameboy. Battery saves are savegame memories that are present in specific cartridges. (e.g., Pokemon cartridges)

Battery saves are available only if the cartridge supports it.
Save states always work and are not dependent on the cartridge.
